### ISSUE TITLE
Add option for time spent in GC as seconds

### ISSUE THREAD

**Issue by SimenB** [SimenB/node-prometheus-gc-stats#2]
Something like

```js
const promGcStats = require('prometheus-gc-stats');

promGcStats({ seconds: true })();
```

**Comment by tcolgate** [comment]
I thought I'd already updated that to seconds, but clearly not. The metric name is also not standard, (unit should be nanoseconds at least, not nanos)
the gc_count should probably be updated too. nodejs_gc_runs_total maybe?

**Comment by SimenB** [comment]
I agree on both accounts
