### ISSUE TITLE
Adding Prefix 

### ISSUE THREAD

**Issue by hamdshah** [SimenB/node-prometheus-gc-stats#51]
Is there a way currently to add the prefix to the metric.
Just like in `prom-client`

```
collectDefaultMetrics({ prefix: 'my_application_' });
```

**Comment by yvasiyarov** [comment]
Hello @folio-as , 
It would be nice to have prefix support for this metrics.
Can you please review proposed pull request ?

**Comment by SimenB** [comment]
`prometheus-gc-stats 0.6.2 published 🎉`

**Comment by yvasiyarov** [comment]
@SimenB @hamdshah thanks a lot guys! Works like a charm!
