### ISSUE TITLE
Update gc-stats version for Node 12

### ISSUE THREAD

**Issue by markmsmith** [SimenB/node-prometheus-gc-stats#58]
Would it be possible to update the gc-stats dependency to the latest version (currently 1.4.0) in order to support Node 12, now that it's the latest LTS?

**Comment by SimenB** [comment]
It's in semver range, just run `npm upgrade` to get it

**Comment by markmsmith** [comment]
Fair enough, thanks.

**Comment by kamilchm** [comment]
Does the `Currently, 10 is supported.` in README means Node.js 10?

**Comment by SimenB** [comment]
It reflects the version of `prom-client`. It is, however, wrong. Source of truth there is the `peerDependencies` entry in package.json: https://github.com/SimenB/node-prometheus-gc-stats/blob/bbd24960e70745cb1fc74b383a55d9ef716dc57c/package.json#L34-L36.

10, 11 and 12 are supported. All node versions should be supported as well
